import { expect, test } from "@playwright/test";

test("learning consent, diagnostic, plan, check detour and reload recovery", async ({ page }, info) => {
  test.skip(!info.project.name.startsWith("local-"));
  const created = await page.request.post("http://127.0.0.1:8000/api/workspaces", { data: { title: `Learning ${info.project.name}` } });
  const workspace = await created.json();
  const otherTitle = `Other ${info.project.name}`;
  await page.request.post("http://127.0.0.1:8000/api/workspaces", { data: { title: otherTitle } });
  const base = `http://127.0.0.1:8000/api/workspaces/${workspace.id}`;
  const upload = await page.request.post(`${base}/sources/text`, { data: { source_name: "Statistics notes", text: "Mean is sum divided by count. Median is the middle value. Mode is the most frequent value.", settings: {} } });
  expect(upload.ok()).toBeTruthy();
  await page.request.post(`${base}/sources/${(await upload.json()).source.id}/accept`);
  await page.goto(`/?workspace=${workspace.id}`);
  await page.getByLabel("向资料提问").fill("我是新手，应该怎么学？");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await expect(page.getByText("要先做一个 3–5 题的小诊断吗？")).toBeVisible();
  await page.getByLabel("学习目标").fill("Learn mean, median and mode");
  await page.getByRole("button", { name: "开始诊断", exact: true }).click();
  for (let i = 0; i < 3; i++) {
    await expect(page.getByText(`第 ${i + 1} / 3 题`)).toBeVisible();
    await page.getByRole("button", { name: "跳过此题" }).click();
  }
  await page.reload();
  await page.getByRole("button", { name: "生成学习路径" }).click();
  await expect(page.getByRole("heading", { name: "学习路径", exact: true })).toBeVisible();
  await page.getByRole("button", { name: "开始概念 1" }).click();
  await page.getByRole("button", { name: "讲得更深入" }).click();
  await expect(page.getByRole("button", { name: "讲得更深入" })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("button", { name: "检查理解" }).click();
  const prompt = await page.getByRole("group", { name: "检查题目" }).innerText();
  await page.getByRole("button", { name: "先问一个问题" }).click();
  await page.getByLabel("向资料提问").fill("What is mean?");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await page.reload();
  await page.getByRole("button", { name: /继续.*检查/ }).click();
  await expect(page.getByRole("group", { name: "检查题目" })).toHaveText(prompt, { useInnerText: true });
  await page.getByRole("radio", { name: "product", exact: true }).check();
  await page.getByRole("button", { name: "提交答案" }).click();
  await expect(page.getByText("需要复习，再看一次讲解。", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "检查理解" }).click();
  let serverSaved = false;
  let release!: () => void;
  const held = new Promise<void>((resolve) => { release = resolve; });
  await page.route("**/learning/checks/*/answers", async (route) => {
    const response = await route.fetch();
    expect(response.ok()).toBeTruthy();
    serverSaved = true;
    await held;
    await route.fulfill({ response });
  }, { times: 1 });
  await page.getByRole("radio", { name: "sum", exact: true }).check();
  await page.getByRole("button", { name: "提交答案" }).click();
  await expect.poll(() => serverSaved).toBeTruthy();
  await page.getByRole("navigation", { name: "学习主题" }).getByText(otherTitle, { exact: true }).click();
  release();
  await expect(page.getByText("已通过。", { exact: true })).toHaveCount(0);
  await page.getByRole("navigation", { name: "学习主题" }).getByText(workspace.title, { exact: true }).click();
  await expect(page.getByText("已通过。", { exact: true })).toBeVisible();
  await page.reload();
  await expect(page.getByText("已通过。", { exact: true })).toBeVisible();
  const feedback = page.getByRole("status").filter({ hasText: "最近一次检查" });
  await feedback.getByRole("button", { name: "引用 1：Statistics notes" }).click();
  await expect(page.getByRole("complementary", { name: "上下文" })).toContainText("sum divided by count");
  await expect(page.getByRole("button", { name: "开始学习下一个概念" })).toBeVisible();
  await page.screenshot({ path: info.outputPath("learning-loop.png") });
  await page.getByRole("button", { name: "开始学习下一个概念" }).click();
  await page.getByRole("button", { name: "检查理解" }).click();
  await page.getByRole("button", { name: "跳过此题" }).click();
  await page.reload();
  await expect(page.getByText("此题已跳过，尚未评估")).toBeVisible();
  await page.getByRole("button", { name: "确认继续下一步" }).click();
  await page.getByRole("button", { name: "开始学习下一个概念" }).click();
  await page.getByRole("button", { name: "检查理解" }).click();
  await page.getByRole("radio", { name: "sum", exact: true }).check();
  await page.getByRole("button", { name: "提交答案" }).click();
  await expect(page.getByText("这条学习路径已结束。跳过的概念仍标记为未评估。")).toBeVisible();
  await page.reload();
  await expect(page.getByText("未评估", { exact: true })).toHaveCount(1);
  await expect(page.getByText("已完成", { exact: true })).toHaveCount(2);
});

test("dismissed invitation stays dismissed after reload and later questions", async ({ page }, info) => {
  test.skip(!info.project.name.startsWith("local-"));
  const workspace = await (await page.request.post("http://127.0.0.1:8000/api/workspaces", { data: { title: `Dismiss ${info.project.name}` } })).json();
  const base = `http://127.0.0.1:8000/api/workspaces/${workspace.id}`;
  const upload = await (await page.request.post(`${base}/sources/text`, { data: { source_name: "Notes", text: "Mean is sum divided by count.", settings: {} } })).json();
  await page.request.post(`${base}/sources/${upload.source.id}/accept`);
  await page.goto(`/?workspace=${workspace.id}`);
  await page.getByLabel("向资料提问").fill("我是新手，应该怎么学？");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await page.getByRole("button", { name: "继续提问", exact: true }).click();
  await expect(page.getByRole("button", { name: "开始诊断", exact: true })).toHaveCount(0);
  await page.reload();
  await page.getByLabel("向资料提问").fill("怎么学？");
  await page.getByRole("button", { name: "发送", exact: true }).click();
  await expect(page.getByText("怎么学？", { exact: true })).toBeVisible();
  await expect(page.getByRole("button", { name: "开始诊断", exact: true })).toHaveCount(0);
  expect((await (await page.request.get(`${base}/diagnostics/invitation`)).json()).status).toBe("dismissed");
});
